# References:
# - https://github.com/jdhealy/PrettyColors/blob/development/.travis.yml
env:
  global:
    - LC_CTYPE=en_US.UTF-8
os: osx
language: c
matrix:
  exclude:
    # Note: Workaround travis-ci/travis-ci#4681
    # Exclude default job which lacks our included environment variables.
    - os: osx
  include:
    - osx_image: xcode8
      env:
        - XCODE_SDK=macosx
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_SCHEME=BonMot-OSX
          XCODE_DESTINATION="arch=x86_64"
    - osx_image: xcode8
      env:
        - XCODE_SDK=iphonesimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_SCHEME=BonMot-iOS
          XCODE_DESTINATION="name=iPhone 6s"
    - osx_image: xcode8
      env:
        - XCODE_SDK=appletvsimulator
          XCODE_ACTION="build-for-testing test-without-building"
          XCODE_SCHEME=BonMot-tvOS
          XCODE_DESTINATION="name=Apple TV 1080p"
    - osx_image: xcode8
      env:
        - XCODE_SDK=watchsimulator
          XCODE_ACTION=build
          XCODE_SCHEME=BonMot-watchOS
          XCODE_DESTINATION="name=Apple Watch - 38mm"
    - osx_image: xcode8
      env:
        - JOB=CARTHAGE
      script:
        - brew update 1> /dev/null 2> /dev/null
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current
        - for platform in Mac iOS tvOS watchOS; do test -d Carthage/Build/${platform}/BonMot.framework || exit 1; done
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - xcodebuild ${XCODE_ACTION}
      -project BonMot.xcodeproj
      -scheme ${XCODE_SCHEME}
      -sdk ${XCODE_SDK}
      -destination "${XCODE_DESTINATION}"
      CODE_SIGNING_REQUIRED=NO
      CODE_SIGN_IDENTITY=
  - TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 xcodebuild ${XCODE_ACTION}
      -project BonMot.xcodeproj
      -scheme ${XCODE_SCHEME}
      -sdk ${XCODE_SDK}
      -destination "${XCODE_DESTINATION}"
      CODE_SIGNING_REQUIRED=NO
      CODE_SIGN_IDENTITY=      
notifications:
  email: false
