version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  swift-package:
    executor: xcode-14
    steps:
      - setup
      - run: swift build
      - run: swift test

  lint-pod:
    executor: xcode-14
    steps:
      - setup
      - lint-pod

  tests-xcode-14:
    executor: xcode-14
    steps:
      - setup
      - run: make test_all

  tests-xcode-15:
    executor: xcode-15
    steps:
      - setup
      - run: make test_all

  deploy-to-cocoapods:
    executor: xcode-14
    steps:
      - setup
      - run: bundle exec pod trunk push

executors:
  xcode-14:
    macos:
      xcode: "14.3.1"
    resource_class: macos.m1.large.gen1
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
  xcode-15:
    macos:
      xcode: "15.1.0"
    resource_class: macos.m1.large.gen1
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - switch-ruby
      - run: brew install xcbeautify

  switch-ruby:
    description: "Switch Ruby"
    steps:
      - macos/switch-ruby:
          version: "3.1.4" # must match version in .ruby-version
      - run: bundle install

  lint-pod:
    description: "Lints podspec with specified Swift version"
    parameters:
      swift-version:
        type: string
        default: "5.8"
    steps:
      - run: bundle exec pod lib lint --swift-version=<< parameters.swift-version >>

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - swift-package:
          filters:
            tags:
              only: /.*/
      - tests-xcode-14:
          filters:
            tags:
              only: /.*/
      - tests-xcode-15:
          filters:
            tags:
              only: /.*/
      - lint-pod:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          context: CocoaPods
          requires:
            - swift-package
            - tests-xcode-14
            - tests-xcode-15
            - lint-pod
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
