version: 2

jobs:
  danger:
    macos:
      xcode: "9.3.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /Users/distiller/project/build/gems
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - checkout
      # Setup Ruby dependencies
      - restore_cache:
          keys:
            - 2-gems-{{ checksum "Gemfile.lock" }}
            # Fall back to a previous cache if exact match cannot be found
            - 2-gems-
      - run:
          name: Restore Ruby Gems
          command: |
            gem install bundler
            bundle check || bundle install
      # Cache Gems
      - save_cache:
          key: 2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - "/Users/distiller/project/build/gems"
      - run:
          name: Install xchtmlreport
          command: |
            brew install https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb
      - run:
          name: Tests & Code Coverage
          when: always
          command: |
            bundle exec fastlane coverage_all
      # Store xcov Code Coverage HTML report artifact 
      - store_artifacts:
          path: /Users/distiller/project/build/BonMot-iOS/xcov
          destination: xcov
      - store_artifacts:
          path: /Users/distiller/project/build/BonMot-iOS/slather
          destination: slather
      - store_artifacts:
          path: /Users/distiller/project/build/BonMot-iOS/scan
          destination: scan
      - run:
          name: Rename CircleCI JUnit XML
          when: always
          command: |
            mkdir -p build/test-results/danger
            cp build/BonMot-iOS/scan/BonMot-iOS.test_result/report.junit build/test-results/danger/results.xml
      - store_test_results:
          path: /Users/distiller/project/build/test-results
      # Install SwiftLint only before Danger because otherwise it fails the build
      - run:
          name: Install SwiftLint
          when: always
          command: |
            brew install swiftlint
      - run:
          name: Danger
          when: always
          command: |
            bundle exec danger
      - run:
          name: Upload to Codecov
          when: always
          command: bash <(curl -s https://codecov.io/bash) -f build/BonMot-iOS/slather/cobertura.xml -X coveragepy -X gcov -X xcode

  test-xcode-10-0:
    macos:
      xcode: "10.0.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /Users/distiller/project/build/gems
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - checkout
      # Setup Ruby dependencies
      - restore_cache:
          keys:
            - 2-gems-{{ checksum "Gemfile.lock" }}
            # Fall back to a previous cache if exact match cannot be found
            - 2-gems-
      - run:
          name: Restore Ruby Gems
          command: |
            gem install bundler
            bundle check || bundle install
      # Cache Gems
      - save_cache:
          key: 2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - "/Users/distiller/project/build/gems"
      - run: ./scripts/macOS.sh
      - run: ./scripts/iOS-12.0.sh
      - run: ./scripts/tvOS-12.0.sh
      - run: ./scripts/watchOS-5.0.sh
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle exec pod lib lint

  test-xcode-9-3:
    macos:
      xcode: "9.3.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /Users/distiller/project/build/gems
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - checkout
      # Setup Ruby dependencies
      - restore_cache:
          keys:
            - 2-gems-{{ checksum "Gemfile.lock" }}
            # Fall back to a previous cache if exact match cannot be found
            - 2-gems-
      - run:
          name: Restore Ruby Gems
          command: |
            gem install bundler
            bundle check || bundle install
      # Cache Gems
      - save_cache:
          key: 2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - "/Users/distiller/project/build/gems"
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: ./scripts/macOS.sh
      - run: ./scripts/iOS-11.3.sh
      - run: ./scripts/tvOS-11.3.sh
      - run: ./scripts/watchOS-4.3.sh
      - run: bundle exec pod lib lint
  test-xcode-9-2:
    macos:
      xcode: "9.2.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /Users/distiller/project/build/gems
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - checkout
      # Setup Ruby dependencies
      - restore_cache:
          keys:
            - 2-gems-{{ checksum "Gemfile.lock" }}
            # Fall back to a previous cache if exact match cannot be found
            - 2-gems-
      - run:
          name: Restore Ruby Gems
          command: |
            bundle check || bundle install
      # Cache Gems
      - save_cache:
          key: 2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - "/Users/distiller/project/build/gems"
      - run: ./scripts/macOS.sh
      - run: ./scripts/iOS-10.3.1.sh
      - run: ./scripts/tvOS-10.2.sh

  carthage-build:
    macos:
      xcode: "9.3.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; brew install carthage --force-bottle)
      - run: carthage build --no-skip-current && for platform in Mac iOS tvOS watchOS; do test -d Carthage/Build/${platform}/BonMot.framework || exit 1; done

  deploy-to-cocoapods:
    macos:
      xcode: "9.3.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /Users/distiller/project/build/gems
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - checkout
      # Setup Ruby dependencies
      - restore_cache:
          keys:
            - 2-gems-{{ checksum "Gemfile.lock" }}
            # Fall back to a previous cache if exact match cannot be found
            - 2-gems-
      - run:
          name: Restore Ruby Gems
          command: |
            bundle check || bundle install
      # Cache Gems
      - save_cache:
          key: 2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - "/Users/distiller/project/build/gems"
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle exec pod trunk push

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - danger:
          filters:
            tags:
              only: /.*/
      - test-xcode-10-0:
          filters:
            tags:
              only: /.*/
      - test-xcode-9-3:
          filters:
            tags:
              only: /.*/
      - test-xcode-9-2:
          filters:
            tags:
              only: /.*/
      - carthage-build:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test-xcode-10-0
            - test-xcode-9-3
            - test-xcode-9-2
            - carthage-build
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
