version: 2.1

jobs:
  danger:
    executor: xcode-10
    steps:
      - setup
      - run:
          name: Install xchtmlreport
          command: |
            brew install https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb
      - run:
          name: Tests & Code Coverage
          when: always
          command: |
            bundle exec fastlane coverage_all
      # Store xcov Code Coverage HTML report artifact
      - store_artifacts:
          path: build/BonMot-iOS/xcov
          destination: xcov
      - store_artifacts:
          path: build/BonMot-iOS/slather
          destination: slather
      - store_artifacts:
          path: build/BonMot-iOS/scan
          destination: scan
      - run:
          name: Rename CircleCI JUnit XML
          when: always
          command: |
            mkdir -p build/test-results/danger
            cp build/BonMot-iOS/scan/BonMot-iOS.test_result/report.junit build/test-results/danger/results.xml
      - store_test_results:
          path: build/test-results
      # Install SwiftLint only before Danger because otherwise it fails the build
      - run:
          name: Install SwiftLint
          when: always
          command: |
            brew install swiftlint
      - run:
          name: Danger
          when: always
          command: |
            if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then bundle exec danger; else echo "Skipping Danger for forked pull request."; fi
      - run:
          name: Upload to Codecov
          when: always
          command: bash <(curl -s https://codecov.io/bash) -f build/BonMot-iOS/slather/cobertura.xml -X coveragepy -X gcov -X xcode

  build-xcode-11:
    executor: xcode-11
    steps:
      - setup
      - run: swift build

  test-xcode-10-2:
    executor: xcode-10
    steps:
      - setup
      - run: ./scripts/macOS.sh SWIFT_VERSION=5
      - run: ./scripts/iOS-11.4.sh SWIFT_VERSION=5
      - run: ./scripts/iOS-12.2.sh SWIFT_VERSION=5
      - run: ./scripts/tvOS-12.2.sh SWIFT_VERSION=5
      - run: ./scripts/watchOS-5.2.sh SWIFT_VERSION=5
      - lint-pod:
          swift-version: "5.0"

  test-xcode-10-1:
    executor: xcode-10
    macos:
      xcode: "10.1.0"
    steps:
      - setup
      - run: ./scripts/macOS.sh SWIFT_VERSION=4.2
      - run: ./scripts/iOS-12.1.sh SWIFT_VERSION=4.2
      - run: ./scripts/tvOS-11.2.sh SWIFT_VERSION=4.2
      - run: ./scripts/tvOS-12.1.sh SWIFT_VERSION=4.2
      - run: ./scripts/watchOS-5.1.sh SWIFT_VERSION=4.2
      - lint-pod:
          swift-version: "4.2"

  carthage-build:
    executor: xcode-10
    steps:
      - checkout
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; brew install carthage --force-bottle)
      - run: carthage build --no-skip-current && for platform in Mac iOS tvOS watchOS; do test -d Carthage/Build/${platform}/BonMot.framework || exit 1; done

  deploy-to-cocoapods:
    executor: xcode-10
    steps:
      - setup
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle exec pod trunk push


executors:
  xcode-11:
    macos:
      xcode: "11.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
  xcode-10:
    macos:
      xcode: "10.2.1"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - restore-gems

  restore-gems:
    description: "Restore Ruby Gems"
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.5" > ~/.ruby-version
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  lint-pod:
    description: "Lints podspec with specified Swift version"
    parameters:
      swift-version:
        type: string
        default: "5.0"
    steps:
      - run: bundle exec pod lib lint --swift-version=<< parameters.swift-version >>

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - danger:
          filters:
            tags:
              only: /.*/
      - test-xcode-10-2:
          filters:
            tags:
              only: /.*/
      - test-xcode-10-1:
          filters:
            tags:
              only: /.*/
      - carthage-build:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test-xcode-10-2
            - test-xcode-10-1
            - carthage-build
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
